<template>
    <div :class="cellClass" > </div>
</template>

<script>
export default {
    name: "GameCell",
    props: ["cellClass"],
    updated() {
        console.log("cell updating")
    }
}
</script>

<style scoped>
.ghost {
    opacity: 0.6;
}

.invisible {
    opacity: 0;
}

.game-grid-cell {
    height: 10px;
    width: 10px;
}

.game-grid-snake-body {
    height: 10px;
    width: 10px;
    background-color: purple;
}

.is-wall {
    background-color: black;
    opacity: 1;
}

.game-grid-snake-food {
    opacity: 1;
    height: 10px;
    width: 10px;
    border-radius: 100% 100% 70% 70%;
    background-color: brown;
    border: 0.5px solid black;
    margin: -1px;

    -webkit-animation: jello-vertical 1.5s infinite both;
	animation: jello-vertical 1.5s infinite both;
}

/* .game-grid-snake-food::after {
    height: 10px;
    width: 10px;
    z-index: 3000;
    content: ' ';
    display: block;
    background-image: url("../assets/egg.svg");
    background-size: 10px 10px;
} */

.food-type-0 {
    background-color: green; 
}

.food-type-1 {
    background-color: blue; 
}

.food-type-2 {
    background-color: red; 
}

.food-type-3 {
    background-color: magenta; 
}

.food-type-4 {
    background-color: darkgrey; 
}

.food-type-5 {
    background-color: yellow; 
}

.food-type-6 {
    background-color: orange; 
}

.food-type-7 {
    background-color: black; 
}

.food-type-8 {
    background-color: white; 
    animation: blink-1 5s linear infinite both;
    -webkit-animation: blink-1 5s linear infinite both;
}


.game-grid-snake-head {
    height: 10px;
    width: 10px;
    background-color: rgb(45, 0, 65);
    opacity: 1;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-8 19:15:49
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-vertical
 * ----------------------------------------
 */
@-webkit-keyframes jello-vertical {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    -webkit-transform: scale3d(0.85, 1.15, 1);
            transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-vertical {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    -webkit-transform: scale3d(0.85, 1.15, 1);
            transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}

@-webkit-keyframes blink-1 {
  0% {
      opacity: 0;
  }
  60% {
      opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes blink-1 {
  0% {
      opacity: 0;
  }
  60% {
      opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

</style>